ALTER TABLE CLIENTI DROP CONSTRAINT FK_CLIENTI_ADRESE_IDADRESA
ALTER TABLE CLIENTI DROP CONSTRAINT FK_CLIENTI_FILIALA_IDFILIALA
ALTER TABLE CONTURI DROP CONSTRAINT FK_CONTURI_STATUSCONT_CODSTATUS
ALTER TABLE CONTURI DROP CONSTRAINT FK_CONTURI_CLIENTI_IDCLIENT
ALTER TABLE CONTURI DROP CONSTRAINT FK_CONTURI_TIPCONT_CODTIPCONT
ALTER TABLE FILIALA DROP CONSTRAINT FK_FILIALA_TIPFILIALA_CODFILIALA
ALTER TABLE FILIALA DROP CONSTRAINT FK_FILIALA_BANCA_IDBANCA
ALTER TABLE FILIALA DROP CONSTRAINT FK_FILIALA_ADRESE_IDADRESA
ALTER TABLE TIPTRANZACTII DROP CONSTRAINT FK_TIPTRANZACTII_TIPTRANZACTII_CODTRANZACTIE
ALTER TABLE TIPTRANZACTII DROP CONSTRAINT FK_TIPTRANZACTII_CONTURI_NRCONT
DROP TABLE ADRESE CASCADE
DROP TABLE BANCI CASCADE
DROP TABLE CLIENTI CASCADE
DROP TABLE CONTURI CASCADE
DROP TABLE FILIALA CASCADE
DROP TABLE STATUSCONT CASCADE
DROP TABLE TIPCONT CASCADE
DROP TABLE TIPFILIALA CASCADE
DROP TABLE TIPTRANZACTII CASCADE
